### PR TITLE
Passkey plugin - Remove redundant calls to passkey-server during message signing

### PR DESCRIPTION
**Pull request by hjornigur**
Suggested solution to #152 

- Add new property to `WebAuthnKey` type - `authenticatorId`, which will be used to form `allowedCredentials` object for signing options while signing a message;
- Modify `toWebAuthnKey` function to include `authenticatorId` in the response;
- Remove passkey-server calls from `toPasskeyValidator`'s `signMessageUsingWebAuthn` function;
- Add couple of helper functions to `utils` to be able to derive all of the required data for signing without reaching out to passkey-server.

### CODE REVIEW

**Comment by adnpark** [comment]
@hjornigur I think it does make sense, and the code looks good to me. Thanks for the contribution. I'll merge it after testing it.

**Comment by hjornigur** [comment]
@adnpark Cool, glad to hear it!
I've noticed that the latest  'main' commit introduced some conflict with the PR, should I resolve the conflict myself before the merge?

UPD:
The conflict turned out to be small so I resolved it myself 🙂

**Comment by adnpark** [comment]
@hjornigur Thanks for resolving the conflict! 

I've pushed a new commit which removes `passkeyServerUrl` (as you said, now we don't need it in `passkeyValidator`. Also fixed some build error regarding `ArrayBuffer`. You can reproduce the error by running `bun run build` inside of `plugins/passkey` directory. (Don't forget to run `bun install` in the root dir) If it doesn't work, just run `bun run build` in the root dir, it will take some time though.

And I've also tested out the new version and it works like a charm. So I think if you're ok with the current code, let's merge it. Whenever it merged, I'll publish new version for it.

**Comment by hjornigur** [comment]
@adnpark Oh, that's interesting, glad the fixed version worked out fine!

I can't reproduce the error in the forked repo (I have some issues regarding resolving peer dependencies in plugins subfolder), but in my project I just don't get any errors regarding passing `Uint8Array` instance as `ArrayBuffer` to the `base64FromArrayBuffer` function, maybe because I have a different node or typescript version where they may have matching interfaces 🤔 And I didn't know that instantiating ArrayBuffer works this way, that's interesting!

Regarding the final code, what do you think of changing the `base64FromArrayBuffer()` to the `base64FromUint8Array()`, and just passing the `hexStringToUint8Array(formattedMessage)` to it?
Since the helper is just used for this single conversion, this change may simplify the flow a little bit

**Comment by adnpark** [comment]
@hjornigur It makes sense. 
I've simplified the encoding process, can you check if it does make sense? And also, I've removed userIds since they were only used for calling `sign-` apis. 
If you're ok with the changes, let me merge it into the main branch now.

**Comment by hjornigur** [comment]
@adnpark Yes, now looks good to me!

**Pull request merged**
